name: Python Package

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - name: Initialize Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Setup Docker Building 
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action/@v2
        with: 
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/flaskdrinks:latest
